apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-clone-app
  labels:
    app: zomato-clone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato-clone-app
  template:
    metadata:
      labels:
        app: zomato-clone-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: zomato-clone-app
        image: pradeepkumara01/zomato:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000